config/routes.rb
Blocitoff::Application.routes.draw do
  resources :todolists 

  get "welcome/index"
  get "welcome/about"
  
  devise_for :users

  match "about" => 'welcome#about', via: :get
  
  root :to =>'welcome#index'
end 

app/models/todolist.rb
class Todolist < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :todolists
  accepts_nested_attributes_for :todolists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  
  respond_to :html, :js
  
  def index
    @todolists = Todolist.all
  end

  def show
    @todolist = Todolist.find(params[:id])
  end

  def new
    @todolist = Todolist.new

  end

  def create
  @todolist = Todolist.new(todolist_params)
  
  if @todolist.save
    flash[:notice] = "Your to-do item was saved."
    redirect_to todolists_url 
  else
    flash[:error] = "There was an error saving your to-do item. Please try again."
    render :new
  end
  end

def destroy
    
    @todolist = Todolist.find(params[:id])
    @todolist.destroy
    
    flash[:notice] = "Successfully destroyed post."
    
    respond_to do |format|
      format.js 
    end
end

  private

  def todolist_params
    params.require(:todolist).permit(:description, :completed)
  end

  def edit
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
    <div class="container">
    <div class="page-header">

      
      
      <ul class="nav nav-tabs pull-right">
        <li><%= link_to "Blocitoff", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "To-dolists", todolists_path %></li> 
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      </ul>

        <h1> Blocitoff<small> // To do list app!</small></h1>
    </div>
    
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/todolists/destroy.js.erb
$('#todolist-' +<%= @todolist.id %>).hide();

app/views/todolists/edit.html.erb
<h1>Todolists#edit</h1>
<p>Find me in app/views/todolists/edit.html.erb</p>

app/views/todolists/index.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
  <h1>My to-do list</h1>
<table class="table">
<thead>
    <tr>
      <th> Description </th>
      <th> Days Created </th>
      <th> Check if completed  </th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
   
  <% @todolists.each  do |todolist| %>
  <%= tag :tr, id: "todolist-#{todolist.id}" %>
  <td><%= todolist.description %></td>
  <td><%=  "#{time_ago_in_words(todolist.created_at)} ago"%> </td> 
   
  <td> 
    
      
    <%= link_to 'Delete to-do item', todolist, method: :delete, remote: true, class: 'btn-sm btn-danger' %> 
          
      </div>
    </div> 
  </td>

  <td><%= link_to 'Show', todolist %></td>
  <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td> 
    </div>
      
  <% end %> 
  </table>
</div>
</div>
<br>

<%= link_to 'New To-do item', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New Todolist</h1>
<div class="row">
  <div class="span6">
    <p> You can submit your new todo items here.</p>
  
    <div class="span 6">
      <%= form_for @todolist do |f| %>
        <div class="control-group">
        <%= f.label :description, class: 'control-label' %>
        <%= f.text_field :description %>
        </div>
        <%= f.submit "Save", class: 'btn btn-primary pull-right' %>
      <% end %>
    </div>
</div>

app/views/todolists/show.html.erb
<h1> @todolist.description</h1>
<p>@todolist.completed</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="text-center"> 
  <h1> Blocitoff</h1>
  <h3> The perfect app for making your smart to do list!</h3>
  <%= link_to "Sign In", new_user_session_path, class: 'btn btn-info btn-large' %> or 
  <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info btn-large' %> today!
  
</div>